const OBLIGATIONS=['ICMS','PIS/COFINS','ISS','SPED ICMS','Fronteiras'];
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return api(request,env,url);return env.ASSETS.fetch(request)}};
async function api(request,env,url){if(!env.DB)return json({error:'Banco D1 não está vinculado ao Worker.'},503);await ensureSchema(env.DB);try{if(url.pathname==='/api/health')return json({ok:true,service:'fiscal-control',version:'clean-online-v1'});if(url.pathname==='/api/auth/login'&&request.method==='POST')return login(request,env);if(url.pathname==='/api/auth/logout'&&request.method==='POST')return logout();const user=await sessionUser(request,env);if(!user)return json({error:'Não autenticado'},401);if(url.pathname==='/api/me')return json({user});if(url.pathname==='/api/state')return state(env.DB,user);if(url.pathname==='/api/executions'&&request.method==='PUT')return updateExecution(request,env.DB,user);if(url.pathname==='/api/stores'&&request.method==='PUT')return updateStore(request,env.DB,user);return json({error:'Rota não encontrada'},404)}catch(e){return json({error:'Erro interno',detail:e.message},500)}}
async function ensureSchema(db){const sql=`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,profile TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS analysts(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,level TEXT,status TEXT NOT NULL DEFAULT 'Ativo');CREATE TABLE IF NOT EXISTS stores(id TEXT PRIMARY KEY,number TEXT UNIQUE NOT NULL,name TEXT NOT NULL,uf TEXT NOT NULL,analyst_id TEXT,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS executions(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,obligation TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Pendente',updated_at TEXT NOT NULL,updated_by TEXT,UNIQUE(store_id,obligation));CREATE TABLE IF NOT EXISTS deadlines(id TEXT PRIMARY KEY,obligation TEXT NOT NULL,uf TEXT NOT NULL,due_date TEXT,note TEXT);CREATE TABLE IF NOT EXISTS audit_log(id TEXT PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,entity TEXT,entity_id TEXT,details TEXT,created_at TEXT NOT NULL);`;for(const s of sql.split(';').map(x=>x.trim()).filter(Boolean))await db.prepare(s).run()}
async function state(db,user){const [analysts,stores,executions,deadlines]=await Promise.all([db.prepare('SELECT id,name,level,status FROM analysts WHERE status=? ORDER BY name').bind('Ativo').all(),user.profile==='Analista'?db.prepare('SELECT s.id,s.number,s.name,s.uf,s.analyst_id,a.name analyst FROM stores s LEFT JOIN analysts a ON a.id=s.analyst_id WHERE s.active=1 AND a.name=? ORDER BY CAST(s.number AS INTEGER),s.name').bind(user.name).all():db.prepare('SELECT s.id,s.number,s.name,s.uf,s.analyst_id,a.name analyst FROM stores s LEFT JOIN analysts a ON a.id=s.analyst_id WHERE s.active=1 ORDER BY CAST(s.number AS INTEGER),s.name').all(),db.prepare('SELECT id,store_id,obligation,status,updated_at,updated_by FROM executions').all(),db.prepare('SELECT id,obligation,uf,due_date,note FROM deadlines ORDER BY due_date').all()]);return json({user,analysts:analysts.results,stores:stores.results,executions:executions.results,deadlines:deadlines.results,obligations:OBLIGATIONS})}
async function login(request,env){const b=await request.json(),username=String(b.username||'').trim(),password=String(b.password||'');if(!username||!password)return json({error:'Informe usuário e senha'},400);const row=await env.DB.prepare('SELECT * FROM users WHERE username=? AND active=1').bind(username).first();if(!row||!(await verify(password,row.password_hash)))return json({error:'Usuário ou senha inválidos'},401);if(!env.SESSION_SECRET)return json({error:'Sessão do servidor não configurada'},503);const token=await sign({id:row.id,exp:Date.now()+28800000},env.SESSION_SECRET);return json({user:{id:row.id,name:row.name,profile:row.profile}},200,{'Set-Cookie':`fc_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`})}
async function logout(){return json({ok:true},200,{'Set-Cookie':'fc_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'})}
async function sessionUser(request,env){if(!env.SESSION_SECRET)return null;const m=(request.headers.get('Cookie')||'').match(/(?:^|; )fc_session=([^;]+)/);if(!m)return null;const d=await unsign(m[1],env.SESSION_SECRET);if(!d||d.exp<Date.now())return null;return env.DB.prepare('SELECT id,name,profile,active FROM users WHERE id=? AND active=1').bind(d.id).first()}
async function updateExecution(request,db,user){const b=await request.json();if(!OBLIGATIONS.includes(b.obligation)||!['Pendente','Analisando','Finalizado'].includes(b.status))return json({error:'Dados inválidos'},400);if(user.profile==='Analista'){const own=await db.prepare('SELECT 1 FROM stores s JOIN analysts a ON a.id=s.analyst_id WHERE s.id=? AND s.active=1 AND a.name=?').bind(b.store_id,user.name).first();if(!own)return json({error:'Você só pode alterar sua própria carteira.'},403)}else if(!['Gerente','Coordenador','Desenvolvedor'].includes(user.profile))return json({error:'Sem permissão'},403);const now=new Date().toISOString();await db.prepare(`INSERT INTO executions(id,store_id,obligation,status,updated_at,updated_by) VALUES(?,?,?,?,?,?) ON CONFLICT(store_id,obligation) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(crypto.randomUUID(),b.store_id,b.obligation,b.status,now,user.id).run();await audit(db,user,'UPDATE','execution',b.store_id,JSON.stringify(b));return json({ok:true})}
async function updateStore(request,db,user){if(!['Gerente','Coordenador','Desenvolvedor'].includes(user.profile))return json({error:'Sem permissão'},403);const b=await request.json();if(!b.id||!b.analyst_id)return json({error:'Dados inválidos'},400);await db.prepare('UPDATE stores SET analyst_id=? WHERE id=?').bind(b.analyst_id,b.id).run();await audit(db,user,'UPDATE','store',b.id,JSON.stringify(b));return json({ok:true})}
async function audit(db,user,action,entity,entityId,details){await db.prepare('INSERT INTO audit_log(id,user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.id,action,entity,entityId,details,new Date().toISOString()).run()}
async function verify(password,stored){try{const [kind,it,saltB64,hashB64]=stored.split(':');if(kind!=='pbkdf2')return false;const salt=Uint8Array.from(atob(saltB64),c=>c.charCodeAt(0)),expected=Uint8Array.from(atob(hashB64),c=>c.charCodeAt(0)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:Number(it),hash:'SHA-256'},key,256),actual=new Uint8Array(bits);return actual.length===expected.length&&actual.every((v,i)=>v===expected[i])}catch{return false}}
async function sign(obj,secret){const payload=btoa(JSON.stringify(obj)).replaceAll('=','');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload));return payload+'.'+btoa(String.fromCharCode(...new Uint8Array(sig))).replaceAll('=','')}
async function unsign(token,secret){try{const [payload,sig]=token.split('.'),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']),ok=await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(sig),c=>c.charCodeAt(0)),new TextEncoder().encode(payload));return ok?JSON.parse(atob(payload)):null}catch{return null}}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8',...headers}})}
